version: "3.9"
services:
  database:
    image: "postgres:14-alpine"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Root
      POSTGRES_DB: restapi_dev
    ports:
      - 5432:5432

  restapi:
    build:
      context: .
    depends_on:
      - database
    ports:
      - 8080:8080

      